### ISSUE TITLE
Wrong Result When Render With ROI 

### ISSUE THREAD

**Issue by euivmar** [meiqua/pose_refine#5]
First of all, thank you for your code! 

I have tried the renderer_test  (test.cpp) changing the ROI as follows :
` cuda_renderer::Model::ROI roi = {320, 240, 100, 100};`

And it give me the following result 
![2019-10-15 17_25_01-gpu_depth_roi](https://user-images.githubusercontent.com/11088553/66845752-e93d6000-ef70-11e9-90e4-ba8e335d9930.png)

When it should be:
![2019-10-15 17_24_26-gpu_depth](https://user-images.githubusercontent.com/11088553/66845768-f35f5e80-ef70-11e9-9c5f-4b3c232e8c9d.png)

Any clue why it is not working properly? 

 A second point I would like to raise relates about timing. The GPU ICP performance it's very impressive, good job! however this code: 

`device_vector_holder<::Vec3f> pcd_buffer_cuda, normal_buffer_cuda;
	scene.init_Scene_projective_cuda(scene_depth, K_, pcd_buffer_cuda, normal_buffer_cuda);` 

is about ten times slower than the ICP, why is it so slow?  do you have any advice for improving its perfomance?  Obviously, using a ROI will help and that's why it is so important that works properly the render with a ROI. 

Thank you!

**Comment by meiqua** [comment]
Oops, [buffer idx](https://github.com/meiqua/pose_refine/blob/e7d7aa0e3f6cdbb0bcdd8ec714de1a30ea366f16/cuda_renderer/renderer.cpp#L247) here is wrong, it should be
```c++
            size_t x_to_write = (P[0] - roi.x);
```
Same for [cuda side](https://github.com/meiqua/pose_refine/blob/e7d7aa0e3f6cdbb0bcdd8ec714de1a30ea366f16/cuda_renderer/renderer.cu#L141)

It's much slower because the initial parts are totally on cpu. You can rewrite it (mainly normals) if caring about the speed.

**Comment by euivmar** [comment]
Thank you for your quick reply!  now it works well.
